/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestFormRouteImport } from './routes/test-form'
import { Route as IndexRouteImport } from './routes/index'

const TestFormRoute = TestFormRouteImport.update({
  id: '/test-form',
  path: '/test-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-form': typeof TestFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-form': typeof TestFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-form': typeof TestFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-form'
  id: '__root__' | '/' | '/test-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestFormRoute: typeof TestFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-form': {
      id: '/test-form'
      path: '/test-form'
      fullPath: '/test-form'
      preLoaderRoute: typeof TestFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestFormRoute: TestFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
